name: tubescribe
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py310h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.19=h6fa692b_0
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - bidict==0.23.1
      - blinker==1.9.0
      - certifi==2026.1.4
      - cuda-bindings==12.9.4
      - distro==1.9.0
      - dotenv==0.9.9
      - flask==3.1.2
      - flask-cors==6.0.2
      - flask-socketio==5.6.0
      - flask-sqlalchemy==3.1.1
      - greenlet==3.3.1
      - idna==3.11
      - itsdangerous==2.2.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==1.2.10
      - langchain-core==1.2.13
      - langchain-openai==1.1.9
      - langgraph==1.0.8
      - langgraph-checkpoint==4.0.0
      - langgraph-prebuilt==1.0.7
      - langgraph-sdk==0.3.6
      - langsmith==0.7.3
      - more-itertools==10.8.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.6.77
      - openai==2.21.0
      - openai-whisper==20250625
      - orjson==3.11.7
      - ormsgpack==1.12.2
      - python-dotenv==1.2.1
      - python-engineio==4.13.1
      - python-socketio==5.16.1
      - pyyaml==6.0.3
      - requests-toolbelt==1.0.0
      - simple-websocket==1.1.0
      - sqlalchemy==2.0.46
      - tenacity==9.1.4
      - tiktoken==0.12.0
      - torch==2.10.0+cu126
      - torchaudio==2.10.0+cu126
      - torchvision==0.25.0+cu126
      - triton==3.6.0
      - uuid-utils==0.14.0
      - werkzeug==3.1.5
      - wsproto==1.3.2
      - xxhash==3.6.0
      - yt-dlp==2026.2.4
      - zstandard==0.25.0
